# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gq7VXWDtY6TxhoQUbTzhvrvrjFgM51hK
"""

a=int(input())
b=int(input())
c=int(input())
d=a+b+c
if(d>50):
  print(d-d/10)
else:
  print(d)